import type { LangCode } from "./types";

/**
 * Phrase dictionary keyed by the exact English string used in the UI.
 * English always stays the main line; the local language is shown as a
 * smaller second line under it (see <Bi /> in components/ui-kit.tsx).
 */
type Phrases = Record<string, string>;

const hi: Phrases = {
  // navigation & shell
  Home: "होम",
  Products: "प्रोडक्ट",
  "AI Studio": "एआई स्टूडियो",
  Orders: "ऑर्डर",
  More: "और",
  Dashboard: "डैशबोर्ड",
  "My Business": "मेरा व्यापार",
  Inventory: "स्टॉक",
  Marketing: "प्रचार",
  Finance: "पैसा",
  "Business Advisor": "व्यापार सलाहकार",
  "My Store": "मेरी दुकान",
  Customers: "ग्राहक",
  Logistics: "डिलीवरी",
  "B2B Marketplace": "बड़े बाज़ार",
  Learning: "सीखें",
  Analytics: "रिपोर्ट",
  Notifications: "सूचनाएं",
  Profile: "प्रोफ़ाइल",
  Settings: "सेटिंग",
  Help: "मदद",
  "Online Presence": "ऑनलाइन पहचान",
  Close: "बंद करें",
  Save: "सेव करें",
  Cancel: "रद्द करें",
  Back: "वापस",
  Next: "आगे",
  Continue: "आगे बढ़ें",
  Done: "हो गया",
  Share: "साझा करें",
  Edit: "बदलें",
  Delete: "हटाएं",
  Speak: "बोलिए",
  // common screens
  "Add Product": "प्रोडक्ट जोड़ें",
  "Create Advertisement": "विज्ञापन बनाएं",
  "Check Price": "कीमत देखें",
  "Record Sale": "बिक्री दर्ज करें",
  "Check Finance": "हिसाब देखें",
  "Generate Content": "कंटेंट बनाएं",
  "Business Health": "व्यापार की सेहत",
  "View Business Health": "पूरी रिपोर्ट देखें",
  "Quick actions": "तुरंत काम",
  "Today's snapshot": "आज का हाल",
  "Your catalogue": "आपके प्रोडक्ट",
  "Ask AI": "एआई से पूछें",
  Sales: "बिक्री",
  Profit: "मुनाफ़ा",
  Expenses: "खर्च",
  Stock: "स्टॉक",
  Price: "कीमत",
  Cost: "लागत",
  Category: "श्रेणी",
  "Product name": "प्रोडक्ट का नाम",
  "Low stock": "स्टॉक कम",
  "Out of stock": "स्टॉक खत्म",
  "Pending payments": "बाकी पैसा",
  "Coming soon": "जल्द आ रहा है",
  "Fair Price Assistant": "सही कीमत सहायक",
  "AI Product Studio": "एआई फोटो स्टूडियो",
  "Voice Cataloguing": "आवाज़ से सूची",
  "Content Transformer": "कंटेंट बनाने वाला",
  "Advertisement Generator": "विज्ञापन बनाने वाला",
  "Reel Generator": "रील बनाने वाला",
  "Profit & Loss": "लाभ-हानि",
  "Scheme Calculator": "योजना कैलकुलेटर",
  "EMI Calculator": "किस्त कैलकुलेटर",
  "Local Market Research": "स्थानीय बाज़ार जानकारी",
  "Competitor Mapping": "प्रतियोगी नक्शा",
  "Build My Online Store": "मेरी ऑनलाइन दुकान बनाएं",
  "Publish Store": "दुकान प्रकाशित करें",
  "Store Preview": "दुकान देखें",
  Language: "भाषा",
  "Choose your language": "अपनी भाषा चुनिए",
};

const pa: Phrases = {
  Home: "ਘਰ",
  Products: "ਉਤਪਾਦ",
  "AI Studio": "ਏਆਈ ਸਟੂਡੀਓ",
  Orders: "ਆਰਡਰ",
  More: "ਹੋਰ",
  "My Business": "ਮੇਰਾ ਕਾਰੋਬਾਰ",
  Inventory: "ਸਟਾਕ",
  Marketing: "ਪ੍ਰਚਾਰ",
  Finance: "ਹਿਸਾਬ",
  "My Store": "ਮੇਰੀ ਦੁਕਾਨ",
  Customers: "ਗਾਹਕ",
  Logistics: "ਡਿਲੀਵਰੀ",
  Learning: "ਸਿੱਖੋ",
  Analytics: "ਰਿਪੋਰਟ",
  Settings: "ਸੈਟਿੰਗ",
  Help: "ਮਦਦ",
  Close: "ਬੰਦ ਕਰੋ",
  Save: "ਸੰਭਾਲੋ",
  Continue: "ਅੱਗੇ ਵਧੋ",
  Speak: "ਬੋਲੋ",
  "Add Product": "ਉਤਪਾਦ ਜੋੜੋ",
  "Create Advertisement": "ਇਸ਼ਤਿਹਾਰ ਬਣਾਓ",
  "Check Price": "ਕੀਮਤ ਵੇਖੋ",
  "Record Sale": "ਵਿਕਰੀ ਦਰਜ ਕਰੋ",
  "Business Health": "ਕਾਰੋਬਾਰ ਦੀ ਸਿਹਤ",
  Sales: "ਵਿਕਰੀ",
  Profit: "ਮੁਨਾਫ਼ਾ",
  Price: "ਕੀਮਤ",
  Stock: "ਸਟਾਕ",
  Language: "ਭਾਸ਼ਾ",
  "Choose your language": "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
};

const mr: Phrases = {
  Home: "मुख्यपृष्ठ",
  Products: "उत्पादने",
  "AI Studio": "एआय स्टुडिओ",
  Orders: "ऑर्डर",
  More: "अधिक",
  "My Business": "माझा व्यवसाय",
  Inventory: "साठा",
  Marketing: "प्रचार",
  Finance: "हिशेब",
  "My Store": "माझे दुकान",
  Customers: "ग्राहक",
  Logistics: "पोहोच",
  Learning: "शिका",
  Analytics: "अहवाल",
  Settings: "सेटिंग",
  Help: "मदत",
  Close: "बंद करा",
  Save: "जतन करा",
  Continue: "पुढे चला",
  Speak: "बोला",
  "Add Product": "उत्पादन जोडा",
  "Create Advertisement": "जाहिरात तयार करा",
  "Check Price": "किंमत पहा",
  "Record Sale": "विक्री नोंदवा",
  "Business Health": "व्यवसायाचे आरोग्य",
  Sales: "विक्री",
  Profit: "नफा",
  Price: "किंमत",
  Stock: "साठा",
  Language: "भाषा",
  "Choose your language": "तुमची भाषा निवडा",
};

const gu: Phrases = {
  Home: "ઘર",
  Products: "ઉત્પાદનો",
  "AI Studio": "એઆઈ સ્ટુડિયો",
  Orders: "ઓર્ડર",
  More: "વધુ",
  "My Business": "મારો ધંધો",
  Inventory: "સ્ટોક",
  Marketing: "પ્રચાર",
  Finance: "હિસાબ",
  "My Store": "મારી દુકાન",
  Customers: "ગ્રાહકો",
  Logistics: "ડિલિવરી",
  Learning: "શીખો",
  Analytics: "અહેવાલ",
  Settings: "સેટિંગ",
  Help: "મદદ",
  Close: "બંધ કરો",
  Save: "સાચવો",
  Continue: "આગળ વધો",
  Speak: "બોલો",
  "Add Product": "ઉત્પાદન ઉમેરો",
  "Create Advertisement": "જાહેરાત બનાવો",
  "Check Price": "કિંમત જુઓ",
  "Record Sale": "વેચાણ નોંધો",
  "Business Health": "ધંધાની તંદુરસ્તી",
  Sales: "વેચાણ",
  Profit: "નફો",
  Price: "કિંમત",
  Stock: "સ્ટોક",
  Language: "ભાષા",
  "Choose your language": "તમારી ભાષા પસંદ કરો",
};

const bn: Phrases = {
  Home: "হোম",
  Products: "পণ্য",
  "AI Studio": "এআই স্টুডিও",
  Orders: "অর্ডার",
  More: "আরও",
  "My Business": "আমার ব্যবসা",
  Inventory: "মজুত",
  Marketing: "প্রচার",
  Finance: "হিসাব",
  "My Store": "আমার দোকান",
  Customers: "ক্রেতা",
  Logistics: "ডেলিভারি",
  Learning: "শিখুন",
  Analytics: "রিপোর্ট",
  Settings: "সেটিংস",
  Help: "সাহায্য",
  Close: "বন্ধ করুন",
  Save: "সংরক্ষণ",
  Continue: "এগিয়ে যান",
  Speak: "বলুন",
  "Add Product": "পণ্য যোগ করুন",
  "Create Advertisement": "বিজ্ঞাপন বানান",
  "Check Price": "দাম দেখুন",
  "Record Sale": "বিক্রি লিখুন",
  "Business Health": "ব্যবসার স্বাস্থ্য",
  Sales: "বিক্রি",
  Profit: "লাভ",
  Price: "দাম",
  Stock: "মজুত",
  Language: "ভাষা",
  "Choose your language": "আপনার ভাষা বাছুন",
};

const ta: Phrases = {
  Home: "முகப்பு",
  Products: "பொருட்கள்",
  "AI Studio": "ஏஐ ஸ்டுடியோ",
  Orders: "ஆர்டர்",
  More: "மேலும்",
  "My Business": "என் வணிகம்",
  Inventory: "கையிருப்பு",
  Marketing: "விளம்பரம்",
  Finance: "கணக்கு",
  "My Store": "என் கடை",
  Customers: "வாடிக்கையாளர்",
  Logistics: "விநியோகம்",
  Learning: "கற்க",
  Analytics: "அறிக்கை",
  Settings: "அமைப்புகள்",
  Help: "உதவி",
  Close: "மூடு",
  Save: "சேமி",
  Continue: "தொடரவும்",
  Speak: "பேசுங்கள்",
  "Add Product": "பொருள் சேர்",
  "Create Advertisement": "விளம்பரம் உருவாக்கு",
  "Check Price": "விலை பார்",
  "Record Sale": "விற்பனை பதிவு",
  "Business Health": "வணிக ஆரோக்கியம்",
  Sales: "விற்பனை",
  Profit: "லாபம்",
  Price: "விலை",
  Stock: "கையிருப்பு",
  Language: "மொழி",
  "Choose your language": "உங்கள் மொழியைத் தேர்வுசெய்க",
};

const te: Phrases = {
  Home: "హోమ్",
  Products: "ఉత్పత్తులు",
  "AI Studio": "ఏఐ స్టూడియో",
  Orders: "ఆర్డర్లు",
  More: "మరిన్ని",
  "My Business": "నా వ్యాపారం",
  Inventory: "సరుకు",
  Marketing: "ప్రచారం",
  Finance: "లెక్కలు",
  "My Store": "నా దుకాణం",
  Customers: "కస్టమర్లు",
  Logistics: "డెలివరీ",
  Learning: "నేర్చుకోండి",
  Analytics: "నివేదిక",
  Settings: "సెట్టింగ్‌లు",
  Help: "సహాయం",
  Close: "మూసివేయి",
  Save: "భద్రపరచు",
  Continue: "ముందుకు",
  Speak: "మాట్లాడండి",
  "Add Product": "ఉత్పత్తిని జోడించు",
  "Create Advertisement": "ప్రకటన తయారు చేయి",
  "Check Price": "ధర చూడండి",
  "Record Sale": "అమ్మకం నమోదు",
  "Business Health": "వ్యాపార ఆరోగ్యం",
  Sales: "అమ్మకాలు",
  Profit: "లాభం",
  Price: "ధర",
  Stock: "సరుకు",
  Language: "భాష",
  "Choose your language": "మీ భాషను ఎంచుకోండి",
};

const kn: Phrases = {
  Home: "ಮುಖಪುಟ",
  Products: "ಉತ್ಪನ್ನಗಳು",
  "AI Studio": "ಎಐ ಸ್ಟುಡಿಯೋ",
  Orders: "ಆರ್ಡರ್",
  More: "ಇನ್ನಷ್ಟು",
  "My Business": "ನನ್ನ ವ್ಯಾಪಾರ",
  Inventory: "ದಾಸ್ತಾನು",
  Marketing: "ಪ್ರಚಾರ",
  Finance: "ಲೆಕ್ಕ",
  "My Store": "ನನ್ನ ಅಂಗಡಿ",
  Customers: "ಗ್ರಾಹಕರು",
  Logistics: "ವಿತರಣೆ",
  Learning: "ಕಲಿಯಿರಿ",
  Analytics: "ವರದಿ",
  Settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
  Help: "ಸಹಾಯ",
  Close: "ಮುಚ್ಚಿ",
  Save: "ಉಳಿಸಿ",
  Continue: "ಮುಂದುವರಿಸಿ",
  Speak: "ಮಾತನಾಡಿ",
  "Add Product": "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
  "Create Advertisement": "ಜಾಹೀರಾತು ರಚಿಸಿ",
  "Check Price": "ಬೆಲೆ ನೋಡಿ",
  "Record Sale": "ಮಾರಾಟ ದಾಖಲಿಸಿ",
  "Business Health": "ವ್ಯಾಪಾರದ ಆರೋಗ್ಯ",
  Sales: "ಮಾರಾಟ",
  Profit: "ಲಾಭ",
  Price: "ಬೆಲೆ",
  Stock: "ದಾಸ್ತಾನು",
  Language: "ಭಾಷೆ",
  "Choose your language": "ನಿಮ್ಮ ಭಾಷೆ ಆರಿಸಿ",
};

const DICTS: Partial<Record<LangCode, Phrases>> = { hi, pa, mr, gu, bn, ta, te, kn };

/** Returns the local-language line for an English UI string, or null. */
export function tr(lang: LangCode, english: string): string | null {
  if (lang === "en") return null;
  const dict = DICTS[lang];
  if (!dict) return null;
  const exact = dict[english];
  if (exact) return exact;
  const trimmed = english.trim();
  return dict[trimmed] ?? null;
}
